services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: seekr-backend
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app/backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: seekr-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend